### ISSUE TITLE
Networking / bsdsocket.library not working correctly

### ISSUE THREAD

**Issue by papa923829** [BlitterStudio/amiberry#1359]
I have tested Amiberry and tested my old Saved AMIGA OS Installation from my AMIGA past.
I have set up an AMIGA 040 with normal speed and with bsdsocket.library, RTG and stuff.
It booted all fine. 
I started a game: dynAMIte and clicked on global server list - it should connect to an Server.  And here the problem appears. It does not. It tries forever. Also when I start the server locally, I cannot connect to 127.0.0.1.

I have tested other Software:
- Ibrowse seems to work fine
- AmiTradeCenter seems to work fine
- AWeb seems to work fine
- BlackIRC seems to not work correctly

I don't know how to report properly what works fine and not, also why it does or does not.
However I tested the exact same configuration with WinUAE and it worked correctly. It connects within seconds and also connecting to 127.0.0.1 works fine.

My System is Linux/Debian Bookworm X86_64. 
I tested it on other systems as well, but there was not change of this behavior.
I also tried to connect with MiamiDX/A2065 emulation but it didn't work as well. MiamiDX couldn't retrieve an IP.

**Comment by midwan** [comment]
The bsdsocket.library emulation is largely based on FS-UAE's implementation, since WinUAE's was Windows-specific. Unfortunately, it looks like BlackIRC doesn't connect under FS-UAE either, so there are obviously some issues with the implementation.

**Comment by papa923829** [comment]
> The bsdsocket.library emulation is largely based on FS-UAE's implementation, since WinUAE's was Windows-specific. Unfortunately, it looks like BlackIRC doesn't connect under FS-UAE either, so there are obviously some issues with the implementation.

Ahh that explains I had the exact same issues with FS-UAE.

**Comment by midwan** [comment]
I'll have to take a deep-dive into it and see if I can improve it, but it will probably have to wait a bit. :)

**Comment by giantclambake** [comment]
FWIW I had a look at this using wireshark, and it gives me the impression that we're failing identd (RFC1413) ...that is, I see the initial connection negotiation, and then the remote server sends a packet that we never reply to. I can probably check this further (I know an IRC admin that will look at connection logs for me) ~ I'll need wait until he's back from holidays =)

**Comment by giantclambake** [comment]
Hmmm...okay... pretty easy to see what's not happening ; bit harder to divine why...

![ex](https://imgur.com/vvmW000.png)

That's wireshark pcap using WinUAE v5.3.0 and a clone of the ClassicWB-P96 setup I use for this stuff.

The first 3 exchanges are the client<>server auth, with the client sending an ACK upon completion...// same in amiberry

...then, the client side instantiates a HTTP/GET packet to the server, and the data resources are retrieved in this manner, to build/populate the server list window that appears at the client end.

In amiberry, this HTTP/GET packet is not seemingly generated, nor transmitted to the server. Eventually the server end calls a timeout, and it's wash, rinse, repeat ad infinitum.  I wouldn't expect it to be the bsdsocket.layer's job to generate that packet ....(unless it is being generated but ignored?)....

....the behavior wrt a 'Local' connection is the same in WinUAE as in amiberry ~ you have to launch the 'DServer.exe' process first, for 'Local' connection to work in the client....

....interestingly, (could be a locale/timezone thing), even though the server list window does pop under WinUAE, and lists 2 servers, neither was apparently responding (retransmission packets) and could not be connected to ... so I couldn't confirm whether or not online gameplay actually worked..hmmm...

@papa923829 -- could you connect to either of these servers?

![EX2](https://imgur.com/mNuGOdh.png)

**Comment by papa923829** [comment]
Alright. I've spend many hours at that weeks to find out whats going on.
I'll try to explain everything as good as I can - but in the end I'm afraid that amiberry is "not the only problem" here. 

I tested amiberry (standalone) - I tested WinUAE and installed MorphOS on qemu - and even asked old AMIGA Users to test it. 

1. First AFAIK nobody could even connect to the above servers. neither with WinUAE nor with MorphOS (native)

2. Amiberry: Connecting to the dserver from dynamite **doesn't** work when you use hostname/localhost/127.0.0.1/internal-server-ip     ---  but works when you use the button "local" - I really don't know what the difference is.
When you start the dserver the server is visible in the GLS-network - means the server generally connect to the network
You can see that happens within dserver in the status log.

3. WinUAE: connecting to the dserver as 127.0.0.1/localhost/hostname/local-ip **works(!)** but the dserver kicks you with pingtimeout. Even though you can play in the 15 seconds and the game feels "normal"
Outsiders (other user on the internet) can "connect" (you see them on the dserver) but the client is still connecting and they can't play - the are also kicked with pingtimeout.

5. MorphOS on QEMU: connecting to the dserver as 127.0.0.1/localhost/hostname/local-ip **works(!)** but the dserver kicks you with pingtimeout. The  small difference to WinUAE here is, the client doesn't connect as well - no matter if I do it or outsiders.
Also different: while the dserver seems active - it is not seen in the GLS server and it doesn#t report in the dserver that it is connection. This is probably due to networking problems with qemu. Unfortunately I'n not that familiar with it.

I hope this was kind of clear. So while amiberry has the most problems here, the main problems probably comes from the game/Dynamite itself. A pingtimeout while connecting from localhost makes it look very strange.

So considering the same behavior happens with WinUAE and MorphOS it looks like WinUAE does pretty much everything right. Means if amiberry would "behave" like WinUAE, the network support surely would improve.


Just in case if you think you want to test "MorphOS on qemu" to have a "more native environment" 
You can install it for free. The 30min demo-time is not a problem. Enough for testing.
When the system is installed on a qemu-file hdmos.img and you need the file: openbios-qemu.elf
You can get it from here and also other help http://zero.eik.bme.hu/~balaton/qemu/amiga/

qemu-system-ppc -machine mac99,via=pmu -m 2048 -vga none -device sm501 -boot d -prom-env "boot-device=hd:,boot.img" -bios openbios-qemu.elf -device ide-hd,drive=hd-drive,bus=ide.0 -drive file=hdmos.img,if=none,id=hd-drive,format=raw -serial stdio -nic user,hostfwd=tcp::6318-:6318 -nic user,hostfwd=udp::6318-:6318

If there is anything I can do to further help you feel free to ask. I'm happy to assist.
And thank you for your time to look at this issue.

**Comment by giantclambake** [comment]
Thanks for checking, that's aligned with my findings ; there's more to it than just amiberry getting it wrong. And that's with the winuae based bsdsocket implementation, as well as the bsdsocket code amiberry uses from fs-uae. That makes it hard...

To be clear, when I was referring to failed identd above, that was wrt the blackIRC client...(it is failing there as well ;)

**Comment by giantclambake** [comment]
Looking at the wireshark logs, this roughly concurs with what I'm seeing -> https://objfw.nil.im/tktview/4c4b0ddef1

...that is, *if* waitselect() is ignoring the timeout and waits forever, that would readily explain the wireshark traces I see...

@midwan .... is this still an apparent problem wrt bsdsocket code used in amiberry?

**Comment by midwan** [comment]
I've implemented a fix, which _might_ resolve these errors.

I've only tested it with one simple tool here (sntp -> https://aminet.net/package/comm/net/sntp) which was giving me errors when it tried to open a socket and set a receive timeout (which sounds like what most of these issues are about).
It seems to work correctly after my fix above, so I think this is an improvement. Nothing seems to be negatively affected by my changes, so fingers crossed (or as they say in Sweden, "thumbs hidden").

Please test when you get a chance and let me know?

**Comment by giantclambake** [comment]
I tested sntp as mentioned in `master`, it seemingly works fine now... (was failing in 7.0)...

![ex](https://imgur.com/5iQGXb0.png)

The program 'Dynamix' still fails as before,  with no improvement...

![ex1](https://imgur.com/r9P65E5.png)

**Comment by midwan** [comment]
Thanks for the feedback!

I'll try to run Dynamix on WinUAE under the debugger, to see what's happening, then compare that with Amiberry. Maybe I can find what fails.

**Comment by giantclambake** [comment]
...same test in WinUAE v5.3.1 ....

![ex](https://imgur.com/dekWtN2.png)

As you can see, client instantiates a HTTP connection to server, after the server ACK comes back...

...might help you find where it's coming unraveled....  ;)

**Comment by papa923829** [comment]
I'm not sure if this is obvious, but what version do I need to use to test the latest patch here? Or do I need to build it from git myself?

**Comment by midwan** [comment]
For now (until a new release is published), you'll need to build it from source.

**Comment by giantclambake** [comment]
Retested, still broken ~ HTTP connection to server not starting...

**Comment by midwan** [comment]
Yes, nothing more was done regarding this. I have a separate branch in testing with, but it's not there yet.

**Comment by papa923829** [comment]
I have tested the recently released 7.0.0-RC3.
I have started the dynamite Server (DServer) and it reports it is connected to the GLS and is online.
The global Server List is (still) not working, neither it is possible to connect via 127.0.0.1 to the server (which partially works with WinUAE (it does , but you get kicked after 10 seconds).

Also I have tried to use the now enabled uaenet.device. It seems I can connect with MiamiDX to the internet , but when I start Dynamite Server, Amiberry freezes completely. You cannot even ungrab the mouse anymore. You have to kill it from "outside" (like switch to different VT - ctrl+alt+F3 - and kill amiberry from there). But I suppose this is a complete different problem.

**Comment by midwan** [comment]
The issue with `uaenet.device` and other SLIRP-based network cards, is now fixed in the latest `master`. At least, based on the basic tests that I've done (using Ibrowse and network time-sync tools), it doesn't freeze the system anymore.

**Comment by papa923829** [comment]
Alright guys. I have tested 7.0.6 and used the now working uaenet.device with MiamiDX (from my old installation).
And I was very much surprised about the out coming.

1. I can now open the global server list correctly.  (!)
2. I can connect locally - not with the local button - but with actually entering the local IP 127.0.0.1 - which DIDN'T work before AND the connection is **stable** 
3. I can connect to one of the servers - which is hellhole in Finland - which is also stable. No more ping timeout. 

Unfortunately after playing/testing a few minutes dynamite of the hellhole amiberry completely freezed (again).
But in sum I can say this is a HUGE advancement.
Congrats!

**Comment by VelocityNL** [comment]
I'm trying to get networking running with Amiberry 7.0.6 with a Raspberry Pi 5 (Raspbian Debian OS). I need a static IP for it. I tested with Genesis and Miami.

I've used uaenet.device and A2065 with all the different options (also using A2065.device and Ethernet.device) and the result is always the same. I can ping the IP i've setup, but can't ping anything else (gateway or other servers in my network).

 Thought there might be a firewall on the Raspbian site, but it looks like iptables is disabled.

Is there anything else i can try, or is it just not supported (at the moment)?

Kind Regards,
Dennis

**Comment by midwan** [comment]
Another small bsdsocket.library fix was added recently. In case you want to test with the latest :)

**Comment by dlundqvist** [comment]
I'm trying to get this to work. After managing to give the binary CAP_NET_RAW capability I could get some packets through but it's not working:

Log from Amiberry:
```
24-795 [541 1: uae_start_thread "bsdsocket" function at 0x7cedc0 arg 0x7f7388000c00
24-795 [541 0: THREAD_START
24-796 [541 0: Getprotobyname(icmp) = 0x7f73f7bff2d0
24-796 [541 1: socket(AF_INET,SOCK_RAW,1) -> socket returns Amiga 0, NativeSide 22
24-796 [541 1: setsockopt: sock 22, level 65535, 'name' 4098(8), len 4 -> 0, 0
24-796 [541 0: Socket thread got action 2
24-797 [541 0: Socket thread got action 3
24-797 [541 0: recv2, recvfrom returns -1, errno is 11
24-797 [541 0: recv2, recvfrom returns 84, errno is 11
24-797 [541 0: Socket thread got action 3
24-797 [541 0: recv2, recvfrom returns -1, errno is 11
25-812 [592 0: Sock abort!!
25-813 [592 0: select aborted from signal
25-813 [592 0: Sockabort got 4 bytes
25-813 [592 0: Done read
25-813 [592 1: Socket thread got action 2
25-814 [592 0: Socket thread got action 3
25-814 [592 0: recv2, recvfrom returns -1, errno is 11
25-814 [592 2: recv2, recvfrom returns 84, errno is 11
25-814 [592 0: Socket thread got action 3
25-814 [592 0: recv2, recvfrom returns -1, errno is 11
26-814 [642 0: Sock abort!!
26-814 [642 1: select aborted from signal
26-814 [642 1: Sockabort got 4 bytes
26-814 [642 1: Done read
26-814 [642 1: Socket thread got action 3
26-814 [642 1: recv2, recvfrom returns -1, errno is 11
27-816 [692 0: Sock abort!!
27-816 [692 0: select aborted from signal
27-816 [692 0: Sockabort got 4 bytes
27-816 [692 0: Done read
27-816 [692 0: Socket thread got action 3
27-816 [692 0: recv2, recvfrom returns -1, errno is 11
28-817 [742 0: Sock abort!!
28-817 [742 0: select aborted from signal
28-817 [742 0: Sockabort got 4 bytes
28-817 [742 0: Done read
28-817 [742 0: Socket thread got action 3
28-817 [742 0: recv2, recvfrom returns -1, errno is 11
29-819 [792 0: Sock abort!!
29-819 [792 0: select aborted from signal
29-819 [792 0: Sockabort got 4 bytes
29-819 [792 0: Done read
29-819 [792 0: Socket thread got action 3
29-819 [792 0: recv2, recvfrom returns -1, errno is 11
30-820 [842 0: Sock abort!!
30-820 [842 0: select aborted from signal
30-820 [842 0: Sockabort got 4 bytes
30-820 [842 0: Done read
30-820 [842 0: Socket thread got action 3
30-820 [842 0: recv2, recvfrom returns -1, errno is 11
31-822 [892 0: Sock abort!!
31-822 [892 0: select aborted from signal
31-822 [892 0: Sockabort got 4 bytes
31-822 [892 0: Done read
31-822 [892 0: Socket thread got action 3
31-822 [892 0: recv2, recvfrom returns -1, errno is 11
34-485 [1025 : Sock abort!!
34-485 [1025 : select aborted from signal
34-489 [1025 : Sockabort got 4 bytes
34-489 [1025 : Done read
34-489 [1025 : Socket thread got action 2
34-489 [1025 : Socket thread got action 2
34-489 [1025 : Socket thread got action 2
34-489 [1025 : Socket thread got action 2
34-489 [1025 : Socket thread got action 2
34-489 [1025 : Socket thread got action 2
34-489 [1025 : Socket thread got action 2
34-489 [1025 : Socket thread got action 2
34-490 [1025 : Socket thread got action 3
34-490 [1025 : recv2, recvfrom returns -1, errno is 11
34-490 [1025 : recv2, recvfrom returns 84, errno is 11
34-491 [1025 : Socket thread got action 3
34-491 [1025 : recv2, recvfrom returns 84, errno is 11
34-492 [1025 : Socket thread got action 3
34-492 [1025 : recv2, recvfrom returns 84, errno is 11
34-492 [1025 : Socket thread got action 3
34-492 [1025 : recv2, recvfrom returns 84, errno is 11
34-493 [1025 : Socket thread got action 3
34-493 [1025 : recv2, recvfrom returns 84, errno is 11
34-494 [1025 : Socket thread got action 3
34-494 [1025 : recv2, recvfrom returns 84, errno is 11
34-495 [1025 : Socket thread got action 3
34-495 [1025 : recv2, recvfrom returns 84, errno is 11
34-495 [1025 : Socket thread got action 3
34-495 [1025 : recv2, recvfrom returns 84, errno is 11
34-496 [1025 : Socket thread got action 3
34-496 [1025 : recv2, recvfrom returns -1, errno is 11
35-180 [1059 : Sock abort!!
35-180 [1059 : select aborted from signal
35-180 [1059 : Sockabort got 4 bytes
35-180 [1059 : Done read
35-182 [1059 : Socket thread got action 0
35-183 [1059 : THREAD_END
```

And from ping to gateway (Roadshow):

![Image](https://github.com/user-attachments/assets/7f8e0b41-5861-442c-862f-c41abe80a50b)

This is on Debian testing (6.13.11) with Amiberry 7.0.8 built from source.

Anything I can do to help you troubleshoot this?

**Comment by midwan** [comment]
Thanks for the info, seems like it still needs more work. :)

**Comment by VelocityNL** [comment]
So, i tried a different approach to get AmiExpress on AmiBerry online. This approach works on WinUAE, but i could not get it to work on AmiBerry.

I now use the bsdsocket.library emulation and the native telnet function of AmiExpress. When i want to connect using Telnet, i got a 'unable to connect. connection refused' message. So, there is an (expected) difference in WinUAE and AmiBerry ;)

**Comment by giantclambake** [comment]
FTR, I did retest against `master` after that commit was rolled in, but nothing had improved wrt Dynamite (I didn't grab a look with wireshark at the time, maybe later...but it wouldn't surprise me to find it stuck in the same spot ;)

**Comment by VelocityNL** [comment]
Easter weekend, so i've got some time on my hands and tested some stuff.

Decided to try a Linux distribution for the Pi and choose Manjaro. Compiled Amiberry and it i had the same problem, no Telnet connection. I went back to Raspian and tested with WiFi (only tested with RJ45) and a (working on Raspian) USB network dongle. Both gave me the exact same error.

Then i decided to change the Telnet port to 2300, since i won't be using port 23 when i publish the BBS online, and to my big surprise it worked!  Changed it back to 23, and no dice. Changed it to 1541, just for fun, and that worked too.

So it seems port 23 is somehow blocked somewhere (Raspbian?)... I'm guessing because it's an unsafe ports by today's standards. 

Al tests are done with Raspbian OS, Latest Amiberry and latest AmiExpress version with Kickstart 3.1.

**Comment by giantclambake** [comment]
....Monday is wireshark day.....and with little surprise I found dynamite gagging in the same place ; eventually I traced it back to the first outgoing packet....

...with amiberry, the first part conversation is marked **incomplete** (missing 2 fields including data) ... 

![ex](https://i.imgur.com/Puo9ef7.png)

..by contrast, using WinUAE 5.3.0 (with the same .hdf files setup), this first packet is marked **complete**, including data....

![ex1](https://i.imgur.com/Inx0LhW.png)

...the ACK coming back from the server, in the WinUAE case, contains data ~ with amiberry the ACK exchange received contains **no** data  (this is likely a snowball from preceding incomplete conversation).... matter of fact, I'm not seeing any packets containing data from the amiberry side with these tests...odd...

Either way, if the dynamite client cannot form a correctly constructed packet (with data) to initially send to the server end, this is very unlikely to work ;)

....tests done with  Amiberry current `master` & WinUAE as mentioned (with WINE), bsdsocket.library only, amd64 (trixie)...

**Comment by midwan** [comment]
Thanks for the extra tests and information.

**Comment by giantclambake** [comment]
Tidbit more ... I noted above the throw of `errno 11` in my amiberry.log as well, along with `errno 115` ... testing with a **Debug** build current `master `...

05-834 [2637 : uae_start_thread "bsdsocket" function at 0x68f044 arg 0x7fde48000c00
05-834 [2637 : THREAD_START
05-837 [2637 : Socket thread got action 4
05-892 [2640 : socket(AF_INET,SOCK_STREAM,0) -> socket returns Amiga 0, NativeSide 39
05-892 [2640 : setsockopt: sock 39, level 65535, 'name' 8(9), len 4 -> 0, 0
05-892 [2640 : setsockopt: sock 39, level 65535, 'name' 4099(19), len 4 -> -1, 92
05-892 [2640 : Invalid setsockopt option 0x2001 for level 1   
05-892 [2640 : setsockopt: sock 39, level 65535, 'name' 8193(-1), len 4 -> -1, 92
05-892 [2640 : Ioctl code is 8004667e, flags are 2
05-892 [2640 : nonblocking
05-892 [2640 : Ioctl code is 8004667d, flags are 2050
05-892 [2640 : Socket thread got action 1
05-892 [2640 : Connect returns -1, errno is 115

...the line `Invalid setsockopt option 0x2001 for level 1`  seems very suspicious here...

Question: is there a table of these errno flags?

**Comment by VelocityNL** [comment]
> Just stumbled on this comment and reminded me that on Linux ports <1024 are privileged and user-space processes can't use them without before elevating privileges.

I've should have known that :) Thanks for the reminder :)

**Comment by dlundqvist** [comment]
> Tidbit more ... I noted above the throw of `errno 11` in my amiberry.log as well, along with `errno 115` ... testing with a **Debug** build current `master `...
> 
> 05-834 [2637 : uae_start_thread "bsdsocket" function at 0x68f044 arg 0x7fde48000c00 05-834 [2637 : THREAD_START 05-837 [2637 : Socket thread got action 4 05-892 [2640 : socket(AF_INET,SOCK_STREAM,0) -> socket returns Amiga 0, NativeSide 39 05-892 [2640 : setsockopt: sock 39, level 65535, 'name' 8(9), len 4 -> 0, 0 05-892 [2640 : setsockopt: sock 39, level 65535, 'name' 4099(19), len 4 -> -1, 92 05-892 [2640 : Invalid setsockopt option 0x2001 for level 1 05-892 [2640 : setsockopt: sock 39, level 65535, 'name' 8193(-1), len 4 -> -1, 92 05-892 [2640 : Ioctl code is 8004667e, flags are 2 05-892 [2640 : nonblocking 05-892 [2640 : Ioctl code is 8004667d, flags are 2050 05-892 [2640 : Socket thread got action 1 05-892 [2640 : Connect returns -1, errno is 115
> 
> ...the line `Invalid setsockopt option 0x2001 for level 1` seems very suspicious here...
> 
> Question: is there a table of these errno flags?

I have them in my Debian at `/usr/include/asm-generic/errno-base.h` and `/usr/include/asm-generic/errno.h'. 11 is EAGAIN, and 115 is EINPROGRESS. So it feels like something is not handling the asynchronous nature of some socket operations.

**Comment by giantclambake** [comment]
Thanks ...I think it's something akin to https://stackoverflow.com/questions/10204134/tcp-connect-error-115-operation-in-progress-what-is-the-cause  ...ie; the socket_opts cannot be applied to the stated packet level

**Comment by midwan** [comment]
After the latest changes, I can now run the Dynamite Server locally, and connect to it locally (using localhost).
I still cannot get the server list, but at least now we don't wait forever when trying that. We get a connection failed error.

The BlackIRC issue in connecting is due to Ident failing, which needs a privileged port (113) to work. That will only work if Amiberry runs with root permissions, so it's normal. Still, I've tried to improve logging around that area, to make it more obvious.

**Comment by dlundqvist** [comment]
With HEAD I still can't get this to work:

Pinging my default gateway:
![Image](https://github.com/user-attachments/assets/9046fdeb-213b-4a0b-90e4-524dea5b9997)

Packets in WireShark (looks fine to me):
![Image](https://github.com/user-attachments/assets/0f77f1be-d3ff-40fe-a541-46819d402be1)

amiberry log:
[bsdsocket.log](https://github.com/user-attachments/files/20374393/bsdsocket.log)

It seems to start out OK then something happens during receive (from what I can tell, and then it doesn't recover).

**Comment by midwan** [comment]
@dlundqvist should be a bit better now. There will still be duplicates, and raw sockets are generally not the best scenario to test with, but I tried to make it a bit more reliable at least.

**Comment by dlundqvist** [comment]
Understood. Just saw duplicates as well:

![Image](https://github.com/user-attachments/assets/64573c3b-2c8b-44a3-9571-730545b55bd1)

[bsdsocket-raw.pcapng.gz](https://github.com/user-attachments/files/20380705/bsdsocket-raw.pcapng.gz)

[bsdsocket.log](https://github.com/user-attachments/files/20380698/bsdsocket.log)

I'll switch over to test using "normal" traffic. Thanks for these changes.

**Comment by dlundqvist** [comment]
I switched back to testing with smbfs (from aminet). I mount share "home" from my Synology, and try to build software (https://github.com/paulroberthill/BlueSCSI-toolbox-Amiga) using SAS/C:

![Image](https://github.com/user-attachments/assets/9fc1e773-f6b3-4abc-bf39-712e18a43034)

[bsdsocket.log](https://github.com/user-attachments/files/20380975/bsdsocket.log)

Mounting and navigating to the directory works fine in CLI, and I did not see any issues in Workbench. But building the software hangs. I'll try to get some captures from Wireshark (if I can separate it from the hosts traffic).

**Comment by midwan** [comment]
That could be due to the smbfs implementation as well, I've seen issues with it in the past also (not on Amiberry specifically, even on real Amigas).

**Comment by dlundqvist** [comment]
Could be but same setup works fine in WinUAE (on Windows) and on real hardware. Same problem with smb2fs (also from aminet).

**Comment by giantclambake** [comment]
With those commits, the behavior of the Dynamite client has changed ~ it's not much, but it's significant (because) at least now things are talking enough to generate a MUI dialog (instead of the never ending 'trying to connect' animation)...

![ex](https://i.imgur.com/qiw0FBY.png)

Note: Initially I was able to spawn a MUI dialog of 'please enter a username' or such and similar, but after entering a username, it never happened again, so at a guess the client software caches this --- I later confirmed this using WinUAE/WINE, where in that emulation when you start the Dynamite client, the username (and password) fields are auto filled with what you previously entered here --- with amiberry, these fields are always blank when you start the Dynamite client --- this may be a different quirk altogether, but without the network stuff working properly, it's hard to call...

The reason for testing with WinUAE here, was to make sure it still worked there, remote server was up etc...all working as expected there to get to the server browser window. (connecting/playing not tested, as the first step should be getting amiberry this far imho =)...

Attaching logfile for sake of completeness -- I'll wireshark it in the morning (I'm a bit tired & puffed out after a long squawk ;) 

[amiberry.log.gz](https://github.com/user-attachments/files/20390918/amiberry.log.gz)

**Comment by midwan** [comment]
Yeah, I saw that. It's still not 100% correct, but a bit better than before.

**Comment by giantclambake** [comment]
Starting the Dynamite client this morning, I noted the username/password fields were pre-filled (just like in WinUAE), however clicking the 'Global server list' button initially spawned this error...

 ![ex1](https://i.imgur.com/7nT3m41.png)

Not sure what is going on there (IPC failing somewhere?)....but it still fails to connect with errno 3 ....

....the first outgoing packet is still 'incomplete' .... from WinUAE...

![ex2](https://i.imgur.com/w2c16uY.png)

...by comparison, from amiberry...

![ex3](https://i.imgur.com/7WALadk.png)

As can be seen, with amiberry we're still not setting the FIN or DATA flags --- that kinda makes sense, as the FIN (finish) flag indicates no more data, but if no data is being encapsulated/sent, then the FIN flag is a bit of a non-sequitur here. I can only imagine the DATA in question here is actually client credentials (as opposed to a usual HTTP request), and without that, it's unlikely to ever complete at the server end....

**Comment by Lucretia** [comment]
I'm struggling to get any sana-ii device working, tried cnet (pcmcia), x-surf, a2065 and uaenet, all give me nothing. I want to be able to network to the host machine, if I use RArp or DHCP, it gets an ip of 10.0.2.2, a static ip on my network of 192.168.0.x doesn't work either. Tried AmiTCP and MiamiDx from aminet. Also, just tried unit 2 of uaenet.device which I thought might be my host nic:

```
uaenet.device reset
- 0: SLIRP User Mode NAT (slirp)
- 1: SLIRP + Open ports (21-23,80) (slirp_inbound)
- 2: enp121s0f4u1u4 (enp121s0f4u1u4)
- 3: Pseudo-device that captures on all interfaces (any)
- 4: lo (lo)
- 5: wlp9s0 (wlp9s0)
- 6: enp8s0 (enp8s0)
- 7: docker0 (docker0)
- 8: Bluetooth Linux Monitor (bluetooth-monitor)
- 9: Raw USB traffic, bus number 1 (usbmon12)
- 10: Raw USB traffic, bus number 1 (usbmon11)
- 11: Raw USB traffic, bus number 1 (usbmon10)
- 12: Raw USB traffic, bus number 9 (usbmon9)
- 13: Raw USB traffic, bus number 8 (usbmon8)
- 14: Raw USB traffic, bus number 7 (usbmon7)
- 15: Raw USB traffic, bus number 6 (usbmon6)
- 16: Raw USB traffic, bus number 5 (usbmon5)
- 17: Raw USB traffic, bus number 4 (usbmon4)
- 18: Raw USB traffic, bus number 3 (usbmon3)
- 19: Raw USB traffic, bus number 2 (usbmon2)
- 20: Raw USB traffic, bus number 1 (usbmon1)
- 21: Raw USB traffic, all USB buses (usbmon0)
- 22: Linux netfilter log (NFLOG) interface (nflog)
- 23: Linux netfilter queue (NFQUEUE) interface (nfqueue)
- 24: D-Bus system bus (dbus-system)
- 25: D-Bus session bus (dbus-session)
```

but it doesn't recognise unit 2, so I don't know what that list is for.
